import type { ActivityLog, CRMState, Followup, Lead } from "./types";
import { createId, dateTimeFromOffset, offsetDate } from "./utils";

type SeedLead = Omit<Lead, "id" | "createdAt" | "updatedAt" | "isArchived"> & {
  createdOffset: number;
};

const seedLeadDefinitions: SeedLead[] = [
  {
    leadUrl: "https://www.instagram.com/bluemango_cafe",
    leadName: "Blue Mango Cafe",
    businessName: "Blue Mango Cafe",
    contactPerson: "Arjun Menon",
    phone: "+919876543210",
    email: "hello@bluemango.example",
    industry: "Restaurant",
    location: "Kochi",
    source: "Instagram",
    leadTemperature: "Hot",
    leadStage: "Follow-up Needed",
    serviceInterest: "30 Posters Monthly Package",
    expectedValue: 30000,
    objectionReason: "",
    firstContactDate: offsetDate(-8),
    nextFollowupDate: offsetDate(0),
    remarks:
      "Owner asked for monthly poster package samples. Interested in restaurant festival creatives and menu highlights.",
    assignedTo: "Kris",
    createdOffset: -9,
  },
  {
    leadUrl: "https://www.instagram.com/auraskinclinic",
    leadName: "Aura Skin Clinic",
    businessName: "Aura Skin Clinic",
    contactPerson: "Dr. Meera Nair",
    phone: "+919447771205",
    email: "clinic@auraskin.example",
    industry: "Clinic",
    location: "Calicut",
    source: "Instagram",
    leadTemperature: "Warm",
    leadStage: "Details Sent",
    serviceInterest: "Website",
    expectedValue: 65000,
    objectionReason: "Need Time",
    firstContactDate: offsetDate(-11),
    nextFollowupDate: offsetDate(2),
    remarks:
      "Website enquiry. Sent package details on WhatsApp. Wants to discuss content collection with partner.",
    assignedTo: "Kris",
    createdOffset: -12,
  },
  {
    leadUrl: "https://www.instagram.com/fitcoregym.in",
    leadName: "FitCore Gym",
    businessName: "FitCore Fitness Center",
    contactPerson: "Rahul Varma",
    phone: "+919895551002",
    email: "fitcore@example.com",
    industry: "Fitness",
    location: "Thrissur",
    source: "Referral",
    leadTemperature: "Hot",
    leadStage: "Proposal Sent",
    serviceInterest: "Posters + Website",
    expectedValue: 90000,
    objectionReason: "",
    firstContactDate: offsetDate(-5),
    nextFollowupDate: offsetDate(-1),
    remarks:
      "Wants a launch campaign and landing page. Proposal sent, follow up on package confirmation.",
    assignedTo: "Captain",
    createdOffset: -6,
  },
  {
    leadUrl: "https://www.instagram.com/theloomboutique",
    leadName: "The Loom Boutique",
    businessName: "The Loom Boutique",
    contactPerson: "Nisha Thomas",
    phone: "",
    email: "",
    industry: "Boutique",
    location: "Ernakulam",
    source: "Instagram",
    leadTemperature: "Cold",
    leadStage: "No Response",
    serviceInterest: "Branding",
    expectedValue: 22000,
    objectionReason: "No Response",
    firstContactDate: offsetDate(-17),
    nextFollowupDate: "",
    remarks:
      "No number in profile. DM sent twice. Keep for future brand refresh outreach.",
    assignedTo: "Kris",
    createdOffset: -18,
  },
  {
    leadUrl: "https://www.instagram.com/greenacresbuilders",
    leadName: "Green Acres Builders",
    businessName: "Green Acres Builders",
    contactPerson: "Faisal K",
    phone: "+919633004411",
    email: "sales@greenacres.example",
    industry: "Builders",
    location: "Kannur",
    source: "Cold Call",
    leadTemperature: "Warm",
    leadStage: "Rejected",
    serviceInterest: "Website",
    expectedValue: 75000,
    objectionReason: "Price High",
    firstContactDate: offsetDate(-21),
    nextFollowupDate: "",
    remarks:
      "Rejected due to pricing. Asked to reconnect after next project launch.",
    assignedTo: "Captain",
    createdOffset: -22,
  },
  {
    leadUrl: "https://www.instagram.com/smilecraftdental",
    leadName: "Smile Craft Dental",
    businessName: "Smile Craft Dental Clinic",
    contactPerson: "Anjali S",
    phone: "+919846120089",
    email: "care@smilecraft.example",
    industry: "Clinic",
    location: "Kottayam",
    source: "Instagram",
    leadTemperature: "Cold",
    leadStage: "Contacted",
    serviceInterest: "15 Posters Monthly Package",
    expectedValue: 15000,
    objectionReason: "Already Has Team",
    firstContactDate: offsetDate(-4),
    nextFollowupDate: offsetDate(6),
    remarks:
      "They already have a designer but are open to occasional campaign creatives.",
    assignedTo: "Kris",
    createdOffset: -5,
  },
  {
    leadUrl: "https://www.instagram.com/urbanspicekitchen",
    leadName: "Urban Spice Kitchen",
    businessName: "Urban Spice Kitchen",
    contactPerson: "Joel Mathew",
    phone: "+919745001124",
    email: "contact@urbanspice.example",
    industry: "Restaurant",
    location: "Kochi",
    source: "Instagram",
    leadTemperature: "Warm",
    leadStage: "Follow-up Needed",
    serviceInterest: "One-time Creative",
    expectedValue: 12000,
    objectionReason: "",
    firstContactDate: offsetDate(-2),
    nextFollowupDate: offsetDate(4),
    remarks:
      "Needs a small campaign for new branch opening. Asked for 6 poster estimate.",
    assignedTo: "Captain",
    createdOffset: -3,
  },
  {
    leadUrl: "https://www.instagram.com/sparklesalon",
    leadName: "Sparkle Salon",
    businessName: "Sparkle Salon",
    contactPerson: "Priya Das",
    phone: "+918590221134",
    email: "sparkle@example.com",
    industry: "Salon",
    location: "Aluva",
    source: "Referral",
    leadTemperature: "Hot",
    leadStage: "Won",
    serviceInterest: "30 Posters Monthly Package",
    expectedValue: 30000,
    objectionReason: "",
    firstContactDate: offsetDate(-14),
    nextFollowupDate: offsetDate(10),
    remarks:
      "Converted for monthly posters. Move to Clients when Phase 2 is active.",
    assignedTo: "Kris",
    createdOffset: -15,
  },
  {
    leadUrl: "https://www.instagram.com/apexlegalservices",
    leadName: "Apex Legal Services",
    businessName: "Apex Legal Services",
    contactPerson: "Vivek Iyer",
    phone: "+918281556700",
    email: "office@apexlegal.example",
    industry: "Services",
    location: "Kochi",
    source: "LinkedIn",
    leadTemperature: "Cold",
    leadStage: "Lost",
    serviceInterest: "Maintenance",
    expectedValue: 18000,
    objectionReason: "No Budget",
    firstContactDate: offsetDate(-30),
    nextFollowupDate: "",
    remarks:
      "Needed low-cost maintenance only. Lost for now due to no active budget.",
    assignedTo: "Captain",
    createdOffset: -31,
  },
];

export function createSeedData(): CRMState {
  const leads: Lead[] = seedLeadDefinitions.map((lead) => ({
    ...lead,
    id: createId("lead"),
    isArchived: false,
    createdAt: dateTimeFromOffset(lead.createdOffset, 9),
    updatedAt: dateTimeFromOffset(Math.min(lead.createdOffset + 1, 0), 12),
  }));

  const leadByName = new Map(leads.map((lead) => [lead.leadName, lead]));

  const followups: Followup[] = [
    buildFollowup(leadByName, "Blue Mango Cafe", -7, "WhatsApp", "Details Sent", 0, "Sent poster package samples."),
    buildFollowup(leadByName, "Aura Skin Clinic", -10, "Call", "Asked for Price", 2, "Doctor asked for website pricing."),
    buildFollowup(leadByName, "FitCore Gym", -4, "Meeting", "Proposal Requested", -1, "Scope discussion completed."),
    buildFollowup(leadByName, "The Loom Boutique", -16, "Instagram DM", "No Response", 0, "No response to DM."),
    buildFollowup(leadByName, "Green Acres Builders", -20, "Call", "Rejected", 0, "Rejected due to budget."),
    buildFollowup(leadByName, "Smile Craft Dental", -3, "WhatsApp", "Call Back Later", 6, "Asked to reconnect next week."),
    buildFollowup(leadByName, "Sparkle Salon", -13, "Call", "Converted", 10, "Converted to monthly package."),
  ].filter(Boolean) as Followup[];

  const activityLogs: ActivityLog[] = leads.flatMap((lead) => [
    {
      id: createId("log"),
      leadId: lead.id,
      action: "Lead created",
      oldValue: "",
      newValue: lead.leadStage,
      createdBy: "captain",
      createdAt: lead.createdAt,
    },
    {
      id: createId("log"),
      leadId: lead.id,
      action: "Stage updated",
      oldValue: "New Lead",
      newValue: lead.leadStage,
      createdBy: "captain",
      createdAt: lead.updatedAt,
    },
  ]);

  return { leads, followups, activityLogs };
}

function buildFollowup(
  leadByName: Map<string, Lead>,
  leadName: string,
  dateOffset: number,
  followupType: Followup["followupType"],
  outcome: Followup["outcome"],
  nextOffset: number,
  remarks: string,
): Followup | null {
  const lead = leadByName.get(leadName);
  if (!lead) return null;

  return {
    id: createId("followup"),
    leadId: lead.id,
    followupDate: offsetDate(dateOffset),
    followupType,
    outcome,
    nextFollowupDate: nextOffset ? offsetDate(nextOffset) : "",
    remarks,
    createdBy: "captain",
    createdAt: dateTimeFromOffset(dateOffset, 11),
  };
}
